### ISSUE TITLE
Error INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by outerwinnie** [Wolvan/spdck#1]
I'm getting this error when i click on "finish login" in the Steam Deck. Any idea?

**Comment by Wolvan** [comment]
Oh yeah, that is something I forgot to mention in the steps, my apologies.
In the App you created you have to click on Edit Settings and add the following to the Redirect URIs field:
`http://localhost:49983/callback`
Then try finish login again.
I'll add that to the next version of Spotideck.

**Comment by outerwinnie** [comment]
Okey, i don't get that error anymore but now when i accept the logging request it says "Spotify authenticated!" "Return back to the quick access menu" but it actually doesn't log in. It still says "Log in to Spotify" in the quick menu.

Edit: I tried rebooting too and still the same.
Edit2: I have made a video of the problem (sorry for the quality):
https://streamable.com/qzml67

**Comment by Wolvan** [comment]
Alright, I can confirm that is the case. I'll do a bit of debugging here, thanks for the heads up.
Always love when it works for me and then just stops working as soon as you publish!

**Comment by Wolvan** [comment]
@OuterWinnie I found the issue and will try and implement a fix ASAP.

**Comment by outerwinnie** [comment]
Thanks!

**Comment by Wolvan** [comment]
@OuterWinnie The issue is fixed with v0.1.1. I just need it to be admin approved for it to be installable, but then it should start working.
