### ISSUE TITLE
INVALID_CLIENT_ Invalid redirect URl

### ISSUE THREAD

**Issue by TimestaticYT** [Wolvan/spdck#2]
When ever I've done everything and try to finish loging I always get redirected to a page that says:INVALID_CLIENT_ Invalid redirect URl

Some people on forums mention something having to do with redirect URls but I don't really know for myself

**Comment by Wolvan** [comment]
Hi! Have you made sure to follow Step 4 on the page and added the redirect url to your app on spotify.com?

**Comment by TimestaticYT** [comment]
It wasn't there when I last tried it I don't remember the message being there but now it was. Maybe I was just misreading things. This seems to happen if you login when you forget to enter the redirect thing. Thanks for the help. Would be cool if the plugin could playback itself but idk how feasible that is. Also for some reason whenever I hard power down my deck it logs out. If I put it to sleep it stays logged in tho

**Comment by Wolvan** [comment]
The new step 4 text was introduced in v0.1.1. You might have had the broken 0.1.0 installed.
Could you put the other 2 issues into separate issues, please?
